### ISSUE TITLE
Segmentation fault in wizard

### ISSUE THREAD

**Issue by jerome-arzel** [nv-vn/opam-create#3]
When I answer to the first question (Package name? or Package version? if package name is in argument), when I press enter there is a segmentation fault.

ogen version: 0.1.3
ocaml version: 4.04.0

Dependencies:
~~~
∗  installed conf-m4.1
∗  installed conf-pkg-config.1.0
∗  installed conf-which.1
∗  installed conf-libpcre.1
∗  installed result.1.2
∗  installed ocamlfind.1.6.2
∗  installed base-bytes.base
∗  installed easy-format.1.2.0
∗  installed biniou.1.0.12
∗  installed ppx_tools.5.0
∗  installed ocamlbuild.0.9.3
∗  installed ppx_blob.0.2
∗  installed cppo.1.4.1
∗  installed ocamlify.0.0.1
∗  installed ocamlmod.0.0.8
∗  installed pcre.7.2.3
∗  installed yojson.1.3.3
∗  installed ocaml-inifiles.1.2
∗  installed ppx_deriving.4.1
∗  installed ppx_deriving_yojson.3.0
∗  installed batteries.2.5.3
∗  installed oasis.0.4.7
∗  installed linenoise.0.9.0
~~~

**Comment by nv-vn** [comment]
I don't currently have access to a machine with OCaml installed, so I can't test this right now (I should be able to by tomorrow). My suspicion is that either ogen or one of its dependencies is not compatible with 4.04 but the OPAM package hasn't yet been updated. I'll try to investigate this tomorrow morning, but for now would you mind testing on 4.03 (if you have it installed)?

**Comment by jerome-arzel** [comment]
Same with OCaml 4.03

**Comment by nv-vn** [comment]
I just tested on 4.03 with no problems. I'm trying on 4.04 (with the same dependency versions you have), I'll update this comment on how that goes.

**Comment by nv-vn** [comment]
Hm, my comment edits didn't work. I've tested it out on 4.04 and don't get a segfault. Would you mind sharing what platform you're running on? I've only been able to test this in amd64 Linux.
Anyways, I think the issue might be related to ocaml-linenoise, since much of that is written in C. If possible, could you compile the example program on the ocaml-linenoise repository please? This might give us a better idea of where the segfault is originating from (this seems probable, too, considering that the bug shows up when pressing enter).

**Comment by jerome-arzel** [comment]
I tried the sample code with linenoise 0.9.0, and the error was still there. So I tried with linenoise 1.0.0 with the same code and with the up to date sample code, and it works for both.
It seems that you need to migrate to linenoise 1.0.0.

**Comment by nv-vn** [comment]
All tests passed on the PR. Looks like it's going to be merged :)
(I'll reopen this later if needed)
